[package]
name = "shuairan"
version = "0.1.0"
edition = "2021"
authors = ["Garry Xu <garry.x@outlook.com>"]
description = "ShuaiRan is a lightweight hypervisor designed for bare-metal servers."
license = "Apache-2.0"

[dependencies]
vmm = { path = "../vmm" }