[package]
name = "utils"
version = "0.1.0"
edition = "2021"
authors = ["Garry Xu <garry.x@outlook.com>"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
chrono = "0.4.23"
